CVVERIFY_APP_COMMON_SOURCES = \
    src/app/AppSettings.cpp \
    src/app/AppDefaultsLoader.cpp \
    src/app/AppVersion.cpp \
    src/app/ApplicationContext.cpp \
    src/app/ServiceLocator.cpp \
    src/app/CommandDispatcher.cpp \
    src/core/diagnostics/DiagnosticsLog.cpp \
    src/core/diagnostics/DnnRuntimeInfo.cpp \
    src/core/models/ModelRegistry.cpp \
    src/core/tasks/TaskScheduler.cpp \
    src/core/project/ProjectService.cpp \
    src/core/project/ParameterPresetStore.cpp \
    src/core/detection/DetectionExportService.cpp \
    src/core/detection/DetectionPreprocess.cpp \
    src/core/detection/DetectionRenderComposer.cpp \
    src/core/detection/LabelProvider.cpp \
    src/core/detection/ModelPackageLoader.cpp \
    src/core/detection/OpenCvDnnRunner.cpp \
    src/core/detection/YoloDetectionDecoder.cpp \
    src/core/detection/YoloDetectionStep.cpp \
    src/core/detection/ClassificationOnnxStep.cpp \
    src/core/detection/CustomTensorOnnxStep.cpp \
    src/core/detection/OcrOnnxStep.cpp \
    src/core/detection/KeypointOnnxStep.cpp \
    src/core/detection/SegmentationOnnxStep.cpp \
    src/core/detection/OnnxModelStepFactory.cpp \
    src/core/detection/ModelImportService.cpp \
    src/core/detection/ModelTemplateLoader.cpp \
    src/core/detection/YoloOnnxImportService.cpp \
    src/core/media/ImageFileSource.cpp \
    src/core/media/ImageFolderSource.cpp \
    src/core/media/VideoFileSource.cpp \
    src/core/operators/builtin/AdaptiveThresholdOperator.cpp \
    src/core/operators/builtin/AffineTransformOperator.cpp \
    src/core/operators/builtin/ArtEffectOperator.cpp \
    src/core/operators/builtin/BilateralFilterOperator.cpp \
    src/core/operators/builtin/BoxFilterOperator.cpp \
    src/core/operators/builtin/BrightnessContrastOperator.cpp \
    src/core/operators/builtin/CannyOperator.cpp \
    src/core/operators/builtin/ColorConvertOperator.cpp \
    src/core/operators/builtin/ColorMapOperator.cpp \
    src/core/operators/builtin/ConnectedComponentsOperator.cpp \
    src/core/operators/builtin/CropOperator.cpp \
    src/core/operators/builtin/FlipOperator.cpp \
    src/core/operators/builtin/RotateOperator.cpp \
    src/core/operators/builtin/TemplateMatchOperator.cpp \
    src/core/operators/builtin/ContourDetectOperator.cpp \
    src/core/operators/builtin/CornerDetectOperator.cpp \
    src/core/operators/builtin/EmbossOperator.cpp \
    src/core/operators/builtin/FiberGlowOperator.cpp \
    src/core/operators/builtin/FloodFillOperator.cpp \
    src/core/operators/builtin/GaussianBlurOperator.cpp \
    src/core/operators/builtin/GrabCutOperator.cpp \
    src/core/operators/builtin/GrayscaleOperator.cpp \
    src/core/operators/builtin/HistogramBarOperator.cpp \
    src/core/operators/builtin/HistogramEqualizeOperator.cpp \
    src/core/operators/builtin/HistogramLineOperator.cpp \
    src/core/operators/builtin/HoughCirclesOperator.cpp \
    src/core/operators/builtin/HoughLinesOperator.cpp \
    src/core/operators/builtin/KMeansSegmentationOperator.cpp \
    src/core/operators/builtin/LaplacianOperator.cpp \
    src/core/operators/builtin/LinearAbsTransformOperator.cpp \
    src/core/operators/builtin/MeanBlurOperator.cpp \
    src/core/operators/builtin/MeanShiftSegmentationOperator.cpp \
    src/core/operators/builtin/MedianBlurOperator.cpp \
    src/core/operators/builtin/MorphologyOperator.cpp \
    src/core/operators/builtin/OtsuThresholdOperator.cpp \
    src/core/operators/builtin/PencilSketchOperator.cpp \
    src/core/operators/builtin/PolarTransformOperator.cpp \
    src/core/operators/builtin/PerspectiveTransformOperator.cpp \
    src/core/operators/builtin/ResizeOperator.cpp \
    src/core/operators/builtin/ScharrOperator.cpp \
    src/core/operators/builtin/SiftKeypointsOperator.cpp \
    src/core/operators/builtin/SobelOperator.cpp \
    src/core/operators/builtin/SpecialEffectOperator.cpp \
    src/core/operators/builtin/SurfKeypointsPlaceholderOperator.cpp \
    src/core/operators/builtin/SurfMatchPlaceholderOperator.cpp \
    src/core/operators/builtin/ThresholdOperator.cpp \
    src/core/operators/builtin/TriangleThresholdOperator.cpp \
    src/core/operators/builtin/WatershedSegmentationOperator.cpp \
    src/core/operators/BuiltinOperatorBootstrap.cpp \
    src/core/operators/OperatorSchemaLoader.cpp \
    src/core/operators/OperatorSchemaExporter.cpp \
    src/core/operators/OperatorRegistry.cpp \
    src/core/pipeline/PipelineEngine.cpp \
    src/core/pipeline/PipelineJsonSerializer.cpp \
    src/core/pipeline/BatchPipelineRunner.cpp \
    src/infra/platform/PlatformPaths.cpp \
    src/infra/opencv/OpenCvImageIO.cpp \
    src/infra/opencv/OpenCvQtImageConverter.cpp \
    src/ui/dialogs/ModelConfigEditorDialog.cpp \
    src/ui/dialogs/OperatorParameterDialog.cpp \
    src/ui/dialogs/SystemSettingsDialog.cpp \
    src/ui/dialogs/YoloModelImportDialog.cpp \
    src/ui/mainwindow/MainWindow.cpp \
    src/ui/panels/ExportResultsPanel.cpp \
    src/ui/panels/MediaPanel.cpp \
    src/ui/panels/ParameterPanel.cpp \
    src/ui/panels/PipelinePanel.cpp \
    src/ui/panels/TaskConsolePanel.cpp \
    src/ui/panels/TaskHistoryPanel.cpp \
    src/ui/panels/DiagnosticsPanel.cpp \
    src/ui/panels/ModelListPanel.cpp \
    src/ui/panels/StatisticsPanel.cpp \
    src/ui/widgets/CanvasView.cpp \
    src/ui/widgets/WipeComparisonWidget.cpp \
    src/ui/widgets/FourGridCanvasWidget.cpp \
    src/ui/widgets/PreviewCanvasHost.cpp \
    src/ui/widgets/TimelineWidget.cpp

CVVERIFY_APP_ENTRY_SOURCE = \
    src/main.cpp

CVVERIFY_APP_SOURCES = \
    $$CVVERIFY_APP_COMMON_SOURCES \
    $$CVVERIFY_APP_ENTRY_SOURCE

CVVERIFY_APP_HEADERS = \
    src/app/AppSettings.h \
    src/app/AppDefaultsLoader.h \
    src/app/AppVersion.h \
    src/app/ApplicationContext.h \
    src/app/ServiceLocator.h \
    src/app/CommandDispatcher.h \
    src/core/diagnostics/DiagnosticsLog.h \
    src/core/diagnostics/DnnRuntimeInfo.h \
    src/core/models/ModelRegistry.h \
    src/core/tasks/TaskScheduler.h \
    src/core/tasks/TaskTypes.h \
    src/core/project/ProjectDefinition.h \
    src/core/project/ProjectService.h \
    src/core/project/ParameterPresetStore.h \
    src/core/detection/DetectionExportService.h \
    src/core/detection/DetectionModelDescriptor.h \
    src/core/detection/DetectionPreprocess.h \
    src/core/detection/DetectionRenderComposer.h \
    src/core/detection/DetectionTypes.h \
    src/core/detection/LabelProvider.h \
    src/core/detection/ModelPackageLoader.h \
    src/core/detection/OpenCvDnnRunner.h \
    src/core/detection/YoloDetectionDecoder.h \
    src/core/detection/YoloDetectionStep.h \
    src/core/detection/ClassificationOnnxStep.h \
    src/core/detection/CustomTensorOnnxStep.h \
    src/core/detection/OcrOnnxStep.h \
    src/core/detection/KeypointOnnxStep.h \
    src/core/detection/SegmentationOnnxStep.h \
    src/core/detection/OnnxModelStepFactory.h \
    src/core/detection/ModelImportService.h \
    src/core/detection/YoloOnnxImportService.h \
    src/core/frame/FramePacket.h \
    src/core/media/ImageFileSource.h \
    src/core/media/ImageFolderSource.h \
    src/core/media/IMediaSource.h \
    src/core/media/MediaTypes.h \
    src/core/media/VideoFileSource.h \
    src/core/operators/builtin/AdaptiveThresholdOperator.h \
    src/core/operators/builtin/AffineTransformOperator.h \
    src/core/operators/builtin/ArtEffectOperator.h \
    src/core/operators/builtin/BilateralFilterOperator.h \
    src/core/operators/builtin/BoxFilterOperator.h \
    src/core/operators/builtin/BrightnessContrastOperator.h \
    src/core/operators/builtin/CannyOperator.h \
    src/core/operators/builtin/ColorConvertOperator.h \
    src/core/operators/builtin/ColorMapOperator.h \
    src/core/operators/builtin/ConnectedComponentsOperator.h \
    src/core/operators/builtin/CropOperator.h \
    src/core/operators/builtin/FlipOperator.h \
    src/core/operators/builtin/RotateOperator.h \
    src/core/operators/builtin/TemplateMatchOperator.h \
    src/core/operators/builtin/ContourDetectOperator.h \
    src/core/operators/builtin/CornerDetectOperator.h \
    src/core/operators/builtin/EmbossOperator.h \
    src/core/operators/builtin/FiberGlowOperator.h \
    src/core/operators/builtin/FloodFillOperator.h \
    src/core/operators/builtin/GaussianBlurOperator.h \
    src/core/operators/builtin/GrabCutOperator.h \
    src/core/operators/builtin/GrayscaleOperator.h \
    src/core/operators/builtin/HistogramBarOperator.h \
    src/core/operators/builtin/HistogramEqualizeOperator.h \
    src/core/operators/builtin/HistogramLineOperator.h \
    src/core/operators/builtin/HoughCirclesOperator.h \
    src/core/operators/builtin/HoughLinesOperator.h \
    src/core/operators/builtin/KMeansSegmentationOperator.h \
    src/core/operators/builtin/LaplacianOperator.h \
    src/core/operators/builtin/LinearAbsTransformOperator.h \
    src/core/operators/builtin/MeanBlurOperator.h \
    src/core/operators/builtin/MeanShiftSegmentationOperator.h \
    src/core/operators/builtin/MedianBlurOperator.h \
    src/core/operators/builtin/MorphologyOperator.h \
    src/core/operators/builtin/OtsuThresholdOperator.h \
    src/core/operators/builtin/PencilSketchOperator.h \
    src/core/operators/builtin/PolarTransformOperator.h \
    src/core/operators/builtin/PerspectiveTransformOperator.h \
    src/core/operators/builtin/ResizeOperator.h \
    src/core/operators/builtin/ScharrOperator.h \
    src/core/operators/builtin/SiftKeypointsOperator.h \
    src/core/operators/builtin/SobelOperator.h \
    src/core/operators/builtin/SpecialEffectOperator.h \
    src/core/operators/builtin/SurfKeypointsPlaceholderOperator.h \
    src/core/operators/builtin/SurfMatchPlaceholderOperator.h \
    src/core/operators/builtin/ThresholdOperator.h \
    src/core/operators/builtin/TriangleThresholdOperator.h \
    src/core/operators/builtin/WatershedSegmentationOperator.h \
    src/core/operators/BuiltinOperatorBootstrap.h \
    src/core/operators/OperatorSchemaLoader.h \
    src/core/operators/OperatorSchemaExporter.h \
    src/core/operators/OperatorDescriptor.h \
    src/core/operators/OperatorRegistry.h \
    src/core/pipeline/IPipelineStep.h \
    src/core/pipeline/PipelineDefinition.h \
    src/core/pipeline/PipelineEngine.h \
    src/core/pipeline/PipelineJsonSerializer.h \
    src/core/pipeline/BatchPipelineRunner.h \
    src/infra/platform/PlatformPaths.h \
    src/infra/opencv/OpenCvImageIO.h \
    src/infra/opencv/OpenCvQtImageConverter.h \
    src/ui/dialogs/ModelConfigEditorDialog.h \
    src/ui/dialogs/OperatorParameterDialog.h \
    src/ui/dialogs/SystemSettingsDialog.h \
    src/ui/dialogs/YoloModelImportDialog.h \
    src/ui/mainwindow/MainWindow.h \
    src/ui/panels/ExportResultsPanel.h \
    src/ui/panels/MediaPanel.h \
    src/ui/panels/ParameterPanel.h \
    src/ui/panels/TaskConsolePanel.h \
    src/ui/panels/TaskHistoryPanel.h \
    src/ui/panels/DiagnosticsPanel.h \
    src/ui/panels/ModelListPanel.h \
    src/ui/panels/StatisticsPanel.h \
    src/ui/panels/PipelinePanel.h \
    src/ui/widgets/CanvasView.h \
    src/ui/widgets/WipeComparisonWidget.h \
    src/ui/widgets/FourGridCanvasWidget.h \
    src/ui/widgets/PreviewCanvasHost.h \
    src/ui/widgets/TimelineWidget.h

CVVERIFY_APP_FORMS = \
    src/ui/dialogs/OperatorParameterDialog.ui \
    src/ui/dialogs/SystemSettingsDialog.ui \
    src/ui/dialogs/YoloModelImportDialog.ui \
    src/ui/mainwindow/MainWindow.ui \
    src/ui/panels/ExportResultsPanel.ui

CVVERIFY_TEST_SOURCES = \
    tests/unit/core/test_core_pipeline.cpp \
    tests/unit/core/test_detection_export_service.cpp \
    tests/unit/core/test_detection_render_composer.cpp \
    tests/unit/core/test_main.cpp \
    tests/unit/core/test_app_defaults_loader.cpp \
    tests/unit/core/test_app_version.cpp \
    tests/unit/core/test_command_dispatcher.cpp \
    tests/unit/core/test_dnn_runtime_info.cpp \
    tests/unit/core/test_media_sources.cpp \
    tests/unit/core/test_model_package_loader.cpp \
    tests/unit/core/test_model_registry.cpp \
    tests/unit/core/test_model_template_loader.cpp \
    tests/unit/core/test_onnx_model_step_factory.cpp \
    tests/unit/core/test_operator_schema_loader.cpp \
    tests/unit/core/test_project_service.cpp \
    tests/unit/core/test_operator_registry.cpp \
    tests/unit/core/test_pipeline_serialization.cpp \
    tests/unit/core/test_yolo_decoder.cpp \
    tests/unit/core/test_yolo_detection_step.cpp \
    tests/unit/ui/test_canvas_view.cpp \
    tests/unit/ui/test_export_results_panel.cpp \
    tests/unit/ui/test_mainwindow_menus.cpp \
    tests/unit/ui/test_media_panel.cpp \
    tests/unit/ui/test_parameter_panel.cpp \
    tests/unit/ui/test_pipeline_panel.cpp \
    tests/unit/ui/test_system_settings_dialog.cpp \
    tests/unit/ui/test_timeline_widget.cpp \
    tests/unit/ui/test_yolo_model_import_dialog.cpp \
    tests/integration/test_integration_smoke.cpp

CVVERIFY_TEST_HEADERS =
